// Five small images, one per format the image diff is offered for, embedded rather
// than read from disk so the suite has no fixtures to lose. Each is 16x16 random
// pixels: random on purpose, because a flat colour compresses to so few bytes that
// cutting it in half stops being a meaningful truncation.
//
// Generated once, never regenerated by the suite: a fixture that rebuilds itself is
// a fixture that can silently change what it proves.
internal static class Samples
{
    internal static readonly Dictionary<string, byte[]> ByFormat = new()
    {
        // PNG, 16x16 random pixels (852 bytes)
        ["PNG"] = Convert.FromBase64String(
            "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAADG0lEQVR4nAEQA+/8AOfu52Fe818w5JtILhXK51AHIB4SYXsP"
            + "7afhZHeW/wIr6o7QKoKhdZMPIzfNN5TFIgIhEoYKvP1hm/KKHVyXYrhaALEeMh249jFHGPbpT2JBq9qt+q3qXxUI+0go/PyB"
            + "hUsB4oQExhPBfY9pRVbZUkLhhTldhGYJ2hcxwt3lZabEESENYPtNQ7UBXTMTgiiqG9LlAI9saAgjidLkfx4XWpC8Qy+5Ruap"
            + "RxEJ87efEQom9iKfo0UlJue8FkKutCvyJ9UP/wEHw8L/YWcoF1qnbkMVOCZALrIC521JQ/ODSQfEGESrvGZ7qczF0AW+DeYI"
            + "6Ao1p9UARP6zFCCNVjnm8Yxt08P8oeekJhCOFY+1nglFz+hhDIh5SBg75De8J2Vm84NbBfESBBd12J0xPsHb7NW2eSLYBx9L"
            + "6oFYRZjeSikjWdWeaqakCy+XxKhKN0gnzR440EL/8QSGiaGQ5Anjowv95/xgIfseIzycWdwUDMI0wtlaZMutA6sRTWoh4uUW"
            + "F29ntyNsG8YBY090o0Iwr+xbgII/S2ahi1v0RqicHd0IQxcq8AfOws7VFxLpCoMEWhEPiPfJy5iuAbg7r6jpR9boHcA/Tmjv"
            + "B/oWKNjPtLwI7buhvjPt7ZEKKqmnVryCXO3nq5dhpFH7yAKpc9UvF1uZOJXHkvtxL/bMXgrAFMHK8kXk0b2UGoG8CPhZ1247"
            + "Un+8tIB56V0b2mMEI9IJH5niFFNv9nSuIgU4+S0A514y6SrGbM/loD6qDwjzVLLLNAT+AlqPDtscryPOAe9JfUvQWK8jkzF6"
            + "5yUEkwgbBz8B0cC+hzRi+STBUu2qAu8A8eqzoKB2ZdWDj1tkewQ249VTpiIM9gOT+a6XcECeR6b0Fw3HOA0snh00KaUSRPc+"
            + "ONDDOIXCBelQjup+9UwAcLenuzyl4Y7gnOqiccx/K7m7DLrKxmO8x09aWi3okAtxHVGXC9ggnCurKYw1oCsNAEkx2H1w+q3r"
            + "ybOsqkX8+SUX0rIBwS3tDLkFONfXSn1TwFWkaMfZlYwe8Z06m09bH+J5dJop8ZVYAAAAAElFTkSuQmCC"),
        // GIF, 16x16 random pixels (1086 bytes)
        ["GIF"] = Convert.FromBase64String(
            "R0lGODdhEAAQAIcAADMAAGYAAJkAAMwAAGYzAJkzAP8zAGZmAJlmAP9mAMyZAP+ZAADMAGbMAMzMAAD/ADP/AJn/ADMAM2YA"
            + "M5kAM8wAMwAzMzMzM2YzM5kzM8wzM/8zM2ZmM5lmM8xmMzOZM5mZM8yZM/+ZMwDMMzPMM2bMM5nMM8zMM//MMzP/M2b/M5n/"
            + "M8z/M///MwAAZmYAZpkAZswAZgAzZjMzZmYzZpkzZv8zZjNmZmZmZplmZsxmZgCZZjOZZmaZZpmZZv+ZZmbMZpnMZszMZmb/"
            + "Zpn/Zsz/Zv//ZjMAmWYAmZkAmcwAmQAzmTMzmWYzmZkzmcwzmQBmmTNmmWZmmZlmmcxmmQCZmTOZmWaZmZmZmcyZmf+ZmTPM"
            + "mWbMmZnMmczMmTP/mZn/mcz/mTMAzJkAzDMzzGYzzJkzzMwzzDNmzGZmzJlmzMxmzACZzJmZzMyZzADMzDPMzMzMzDP/zJn/"
            + "zMz/zAAA/2YA/5kA/8wA/wAz/2Yz/5kz/8wz/2Zm/5lm/8xm//9m/zOZ/2aZ/wDM/zPM/2bM/5nM/8zM/zP//wAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACwAAAAAEAAQAEAI"
            + "/wDp9CmTYVAAF3eICMpjogcFEiZwVPmTQs0bHE2m5MCAwQSKBmjeWGDiJg4TCHoWhChTpAsQIB1skLGxA06hLh9WdNE4YceA"
            + "KAvaXDhwKIWHKThYVGASJAwGFVLUmOGT4FCHG08QaIgTocySIVdqUAmiY4uBJFiAECpjoU2MCleeuAHTZcubNRr01IAywsmH"
            + "Ai7sxIniZEwUAEaAbIGDBEYJGTmWCJlhgoeIOgryWLmwAA4JPF+OkPlxqMsRNhSK7Jhw5saPByy4XJkSqAQDEjbkUGlhqIYS"
            + "AE/0ALBBg8mFDYbcNLhBJwgBM1dMGFgDaJCbLloEvHBgokYYCjMK/SMwJAGQGx4+QoggpIBHIBBk/MzJgkjMGAgVTqTp4WWP"
            + "Ew4BAQA7"),
        // BMP, 16x16 random pixels (822 bytes)
        ["BMP"] = Convert.FromBase64String(
            "Qk02AwAAAAAAADYAAAAoAAAAEAAAABAAAAABABgAAAAAAAADAADEDgAAxA4AAAAAAAAAAAAA2DFJ+nB9yeutqqyz+fxF0hcl"
            + "wQGyDO0tOAW5StfXwFN9aKRVldnH8R6MmzqdH1tPp7dwpTy74I7houqcf8xxu7kryroMvGPGWk/H6C1acQuQl1EdINgLqyuc"
            + "NYwpDSugUiwl9794a7X1/a+tPSZE423lx4TZTrxNXpSmMb3aKKXs+N0qBJntbZ4m/ZspSZCnfUnv1Rk6aDzpT7Ya4ro/6dVH"
            + "utaGQZRGOvZ6jLeejmGLf2F6HxRkhIoEEw3ZjnE0jYCEM9SuFyfjxVHF/Vbx/dsdzJHXkrufkYr3Bw2XUBV9G8fRGcuhciWj"
            + "gPTbMhd8hK5hUTuPqETPXN29XmnPmq4kBTPwdhm2rJmLXc9u/scnyj1tNzoL44N5ZBnNMgXArzu49iRgEww2YUv2aDpekFBY"
            + "RB8wMSfs78in3LXaBr9rXGYUuOjQY8+9BzBUzyuldE9jpJEG/321Pv8132WA08ALb2hRd0VuoVyxb2OhRDFjLUN6McaEQNfe"
            + "Cc5mt2YxLPzhlOBxn4NUm2rD/otIOtJmDsECPs0WVS/70+ohfonOQfzy896tYjeihQ/WEgtCi3NbyVGx0ixy5kLGA2To7a/A"
            + "MminfG0/nizHCIakEyqy16/hDvmM2yBvq1gRTPBHs/5EjSAU5jlWbYzx/MPTpOehjhAmtY8VRQmeYejPeYgMOxhIvDfkZmUn"
            + "W4PzEvEFwsMHKSQGgzsuxqnV7OHqng8qC/Ys/jl1BYL4SZq8r1Zne//igM+nZtxlcMRtRWuiaGyPiSMIf+TSWhceQ7yQRrkv"
            + "R6nm8wkREZ+39iYKo58iJiVFFrzntK5CJ/Ir/w/VBITixZeoLiYlB3xq6L68RfdBTl3Ff3SfZFFhKPfGNRjXghM3g8h6lvvX"
            + "QCNZJfV0bQAI8Bpr1svAimUlnyys0QeqfkQ8HgUzWvnuYeVgxNZD18o7igBsawqbM8lfbUoV5+7n815h5DBfLkib58oVIAdQ"
            + "YRIe7Q97ZOGn/5Z36isCKtCOdaGCIw+TN803IsWU"),
        // WEBP, 16x16 random pixels (306 bytes)
        ["WEBP"] = Convert.FromBase64String(
            "UklGRioBAABXRUJQVlA4IB4BAAAwBgCdASoQABAAAUAmJbACdDrQNUA/bv9bvaAKV5/nfIF8of6b3AP45/Mf9bwFH6Xm2mzO"
            + "O79fBgAAAP7CCUM3+7tcTA0StUPx+/AN/Bdj2rgSus/dzwSx+c6TIpci4I1tIzF9RmSwVewLrjw5lpewAVSPmkN4xkVjbkYf"
            + "BYv+wg/rX+wg9FuerwIcqcm+jSZ7YO9Vnldfft/p6ziT4hIPU5xkN+FSYwnf0Ju0h+6IqJ2+1d4tm85PAl94Yp10Npj686VW"
            + "i0FkCsK8mb+hH6QtF2SrrikZGGHu7Bby/FpYyIWgkKqc4tYvzk74p7uOnzWoYHVLIqGuobgq3GChlef/9hx+MkuRdb+zwQ6t"
            + "8Gj0Ov91gFUvaV1lUXeHgAAA"),
        // JPEG, 16x16 random pixels (781 bytes)
        ["JPEG"] = Convert.FromBase64String(
            "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcp"
            + "LDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIy"
            + "MjIyMjIyMjIyMjIyMjL/wAARCAAQABADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAA"
            + "AgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6"
            + "Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXG"
            + "x8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREA"
            + "AgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5"
            + "OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPE"
            + "xcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCrcaYLjT9QF/Az3MU+1Y5TJvIy22XcSCxO"
            + "9Mhjuxuw3RReuCGjk1K/MqJJIghm8sQxpIY8sWKsCWK4VmxgclSM/K1dNgOmQtdNJHb3DM0Gy5Jw/GI+eOSpxtBHDcnqYNQn"
            + "+S8kglVILkKjvHC0Ixt3R5+Q5PUkq2GHGOQQ8Upydtet9+9nrr2vbbe99xqEZXi3d6L0utenXsu3Z6//2Q=="),
    };
}
